### ISSUE TITLE
Can't run app.py

### ISSUE THREAD

**Issue by dvirk** [mick-warehime/sixth_corp#12]
I'm confused by the project structure. In pycharm, I mark the `src` folder as Sources Root. (If I don't do this, then there are import issues. I.e. import references can't be found.) Then if I right click app.py and select "run app.py", I get weird errors. 

Eg, 
```bash
/home/dvirkafri/Projects/sixth_corp/venv/bin/python /home/dvirkafri/Projects/sixth_corp/src/app.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
2018-12-23 19:32:35,737 0.001 [INFO]  Start Application
2018-12-23 19:32:35,737 0.001 [DEBUG]  registered listener 1 <game.Game object at 0x7b1ed1c47780>
2018-12-23 19:32:36,336 0.001 [DEBUG]  registered listener 2 <keyboard.Keyboard object at 0x7b1ec21f9048>
Traceback (most recent call last):
  File "/home/dvirkafri/Projects/sixth_corp/src/app.py", line 47, in <module>
    g = Game()
  File "/home/dvirkafri/Projects/sixth_corp/src/game.py", line 41, in __init__
    self.keyboard = Keyboard(self.event_manager)
  File "/home/dvirkafri/Projects/sixth_corp/src/keyboard.py", line 14, in __init__
    self.bindings.load()
  File "/home/dvirkafri/Projects/sixth_corp/src/keybindings.py", line 18, in load
    with open(self.preference_file) as bindings_file:
FileNotFoundError: [Errno 2] No such file or directory: 'src/data/bindings.pref'
```

Also, an `src` directory is created within the `src` directory and stores logging information.

**Comment by mick-warehime** [comment]
most likely problem is your working directory is project/src and it should be just project. (this is described in readme)
